/* export const ProductList = [
  {
    name: "Ducky One 2 Mecha ",
    brand: "Ducky",
    price: 1690,
    img1: "duckyone2mecha1.webp",
    img2: "duckyone2mecha2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Ducky One 2 Tuxedo",
    brand: "Ducky",
    price: 1290,
    img1: "duckyone2tuxedo1.webp",
    img2: "duckyone2tuxedo2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Ducky One 3 Daybreak SF",
    brand: "Ducky",
    price: 1849,
    img1: "duckyone3daybreaksf1.webp",
    img2: "duckyone3daybreaksf2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Ducky One 3 Matcha",
    brand: "Ducky",
    price: 1490,
    img1: "duckyone3matcha1.webp",
    img2: "duckyone3matcha2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Ducky MIYA Pro Sakura TKL",
    brand: "Ducky",
    price: 1790,
    img1: "DuckyMIYAProSakuraTKL1.webp",
    img2: "DuckyMIYAProSakuraTKL2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Keychron K2 V2",
    brand: "Keychron",
    price: "1190",
    img1: "KeychronK2V21.webp",
    img2: "KeychronK2V22.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Keychron K6",
    brand: "Keychron",
    price: 1190,
    img1: "KeychronK61.webp",
    img2: "KeychronK62.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Keychron K8 Pro",
    brand: "Keychron",
    price: 1189,
    img1: "KeychronK81.webp",
    img2: "keychronK82.webp",
    category: "Keyboards.webp",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Keychron K3 Ultra Slim V2",
    brand: "Keychron",
    price: 1249,
    img1: "KeychronK3UltraslimV21.webp",
    img2: "KeychronK3UltraslimV22.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Keychron K4 v2 ",
    brand: "Keychron",
    price: 1249,
    img1: "Keychronk4v21.webp",
    img2: "keychronk4v22.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Varmilo VA69",
    brand: "Varmilo",
    price: 1149,
    img1: "varmilova691.webp",
    img2: "varmilova692.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Varmilo VEA88 Sea Melody TKL",
    brand: "Varmilo",
    price: 1699,
    img1: "vea88seamelody1.webp",
    img2: "vea88seamelody2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Varmilo VEA109 Panda R2 V2",
    brand: "Varmilo",
    price: 1699,
    img1: "VEA109PandaR2V21.webp",
    img2: "VEA109PandaR2V22.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Varmilo VEA 109 Yakumo V2",
    brand: "Varmilo",
    price: 1999,
    img1: "varmilovea109yakumov21.webp",
    img2: "varmilovea109yakumov22.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Varmilo VEA 88",
    brand: "Varmilo",
    price: 1399,
    img1: "varmilovea881.webp",
    img2: "varmilovea882.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Yunzii CoolKiller CK 75 Mint Green",
    brand: "Yunzii",
    price: 1989,
    img1: "yunziicoolkillerck751.webp",
    img2: "yunziicoolkillerck752.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Yunzii KC84S Milk Honey",
    brand: "Yunzii",
    price: 1100,
    img1: "yunziikc84s1.webp",
    img2: "yunziikc84s2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Yunzii Keynovo IF98",
    brand: "Yunzii",
    price: 1359,
    img1: "yunziikeynovoif98pro1.webp",
    img2: "yunziikeynovoif98pro2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Yunzii Macaron ",
    brand: "Yunzii",
    price: 999,
    img1: "yunziimacaron1.webp",
    img2: "yunziimacaron2.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Yunzii VN66",
    brand: "Yunzii",
    price: 940,
    img1: "yunziivn661.webp",
    img2: "yunziivn662.webp",
    category: "Keyboards",
    qty: 100,
    switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    name: "Cooler Master Thunderstom Purple",
    price: 249,
    img1: "cmthunderstormpurple1.webp",
    img2: "cmthunderstormpurple2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Glorious Coil Cable Phantom Black",
    price: 679,
    img1: "gloriouscoilblack1.webp",
    img2: "gloriouscoilblack2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Keychron Custom Coiled Aviator Cable Black",
    price: 249,
    img1: "keychroncoilblack1.webp",
    img2: "keychroncoilblack2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "MaxMount Premium Aviator Coiled Cable Gray",
    price: 399,
    img1: "maxmountpremiumaviatorgray1.webp",
    img2: "maxmountpremiumaviatorgray2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "MaxMount Premium Aviator Coiled Cable Purple",
    price: 399,
    img1: "premiumaviatorpurple1.webp",
    img2: "premiumaviatorpurple2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "CableMod Pro Coiled Cable Blue",
    price: 569,
    img1: "procoiledblue1.webp",
    img2: "procoiledblue2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "CableMod Pro Coiled Cable Green",
    price: 569,
    img1: "procoiledgreen1.webp",
    img2: "procoiledgreen2.webp",
    brand: "Cables",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Varmilo Mulan Beijing Opera",
    price: 249,
    img1: "MulanBeijingOpera.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Varmilo Daisy",
    price: 249,
    img1: "varmilodaisy.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Varmilo Forest Fairy",
    price: 249,
    img1: "varmiloforestfairy.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Varmilo MousePad XL",
    price: 249,
    img1: "varmilomousepadxl1.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "X Gamer Cyber Bot XXL",
    price: 349,
    img1: "xgamercyberbot.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "X Gamer Ginger Queen XXL",
    price: 399,
    img1: "xgamergingerqueen.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "X Gamer Persian Ruby XXL",
    price: 399,
    img1: "xgamerpersianruby.webp",
    brand: "Desktop Pads",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Ducky Wrist Rest TKL",
    price: 349,
    img1: "duckywristrestTKL.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Glorious Gaming Race Stealth TKL",
    price: 279,
    img1: "gloriousracestealthTKL.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "KBDfans Alopow Resin wrist rest  Galaxy Purple",
    price: 329,
    img1: "kbdfansalopowresingalaxypurple.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Keychron K2/K6 Walnut Wood",
    price: 290,
    img1: "keychronK2K6WalnutWood.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Keychron K8 Walnut Wood",
    price: 290,
    img1: "keychronk8walnutwood.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "MaxMount Wrist Rest TKL",
    price: 149,
    img1: "maxmountwristrestTKL.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
  {
    name: "Xtrfy WR2 Wrist Rest Bamboo",
    price: 279,
    img1: "xtrfywr2bamboo.webp",
    brand: "Wrist Rest",
    category: "Accessories",
    qty: 100,
  },
];
 */
